### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by ishfaq333** [sotzee/quaryonic_eos#1]
I am getting the following error when running the code.

python3 main_eos_table.py
Traceback (most recent call last):
  File "main_eos_table.py", line 10, in <module>
    from joblib import Parallel, delayed
  File "/home/ishfaq/TOVsolver/quaryonic_eos/quaryonic_eos-master/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/home/ishfaq/TOVsolver/quaryonic_eos/quaryonic_eos-master/joblib/parallel.py", line 28, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/ishfaq/TOVsolver/quaryonic_eos/quaryonic_eos-master/joblib/_parallel_backends.py", line 22, in <module>
    from .executor import get_memmapping_executor
  File "/home/ishfaq/TOVsolver/quaryonic_eos/quaryonic_eos-master/joblib/executor.py", line 14, in <module>
    from .externals.loky.reusable_executor import get_reusable_executor
  File "/home/ishfaq/TOVsolver/quaryonic_eos/quaryonic_eos-master/joblib/externals/loky/__init__.py", line 12, in <module>
    from .backend.reduction import set_loky_pickler
  File "/home/ishfaq/TOVsolver/quaryonic_eos/quaryonic_eos-master/joblib/externals/loky/backend/reduction.py", line 125, in <module>
    from joblib.externals import cloudpickle  # noqa: F401
  File "/home/ishfaq/TOVsolver/quaryonic_eos/quaryonic_eos-master/joblib/externals/cloudpickle/__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "/home/ishfaq/TOVsolver/quaryonic_eos/quaryonic_eos-master/joblib/externals/cloudpickle/cloudpickle.py", line 152, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/home/ishfaq/TOVsolver/quaryonic_eos/quaryonic_eos-master/joblib/externals/cloudpickle/cloudpickle.py", line 133, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)

Can you please help me understand what is wrong?

**Comment by sotzee** [comment]
Hi ishfaq,

It’s the issue of joblib library. Recent updated version of python3 are not compatible with the version joblib included with the code. You need to delete the joblib and install latest version of joblib.

Tianqi

**Comment by sotzee** [comment]
From here https://github.com/joblib/joblib

Wish good!

**Comment by ishfaq333** [comment]
Thank you and sorry for the trouble.

It works fine now.

**Comment by sotzee** [comment]
You are welcome!
